version: "3"

services:
  schellar:
    image: flaviostutz/schellar
    environment:
      - CONDUCTOR_API_URL=http://conductor-server:8080/api
      - MONGO_ADDRESS=mongo
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=root
      - LOG_LEVEL=info
    ports:
      - 3000:3000
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "20MB"
        max-file: "5"
    networks:
      - githunter-net

  conductor-server:
    build: ./conductor/server
    image: conductor-server
    environment:
      - DYNOMITE_HOSTS=dynomite:8102:us-east-1c
      - ELASTICSEARCH_URL=http://elasticblast:8200/
      - LOADSAMPLE=false
      - PROVISIONING_UPDATE_EXISTING_TASKS=false
    ports:
      - 8080:8080
    restart: always
    networks:
      - githunter-net

  conductor-ui:
    image: flaviostutz/conductor-ui
    environment:
      - WF_SERVER=http://conductor-server:8080/api/
    ports:
      - 5000:5000
    networks:
      - githunter-net

  dynomite:
    image: flaviostutz/dynomite:0.7.5
    ports:
      - 8102:8102
    networks:
      - githunter-net

  elasticblast:
    image: flaviostutz/elasticblast
    restart: always
    ports:
      - 8200:8200
    environment:
      - LOG_LEVEL=info
      - BLAST_URL=http://blast:6000
    networks:
      - githunter-net

  blast:
    image: flaviostutz/blast-indexer
    ports:
      - 6000:6000
    networks:
      - githunter-net

  # mongo:
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: root
  #   volumes:
  #     - ./data/mongo/volume:/data/db
  #   ports:
  #     - 27017:27017
  #   networks:
  #     - githunter-net

  # scraper:
  #   build: .
  #   image: githunter-scraper:1.0
  #   restart: always
  #   ports:
  #     - 3002:3002
  #   networks:
  #     - githunter-net

networks:
  githunter-net:
