version: '3'

services:

  mongo:
    image: mongo
    restart: always
    environment:
        MONGO_INITDB_DATABASE: githunter-scraper
        MONGO_INITDB_ROOT_USERNAME: githunter
        MONGO_INITDB_ROOT_PASSWORD: G1THuNt3R
        NODE_ENV: docker_dev
    volumes:
        - ./data/mongo/001_users.js:/docker-entrypoint-initdb.d/001_users.js:ro
        - ./data/mongo/volume:/data/db
        - mongodb_config:/data/configdb
    ports:
        - 27017:27017

  api:
    build: .
    image: githunter-scraper:1.0
    restart: always
    ports:
      - 3002:3002

volumes:
    mongodb_config: